@startuml

skinparam style strictuml

actor Caller
participant ":SortCommand" as sort
participant "db:StudentDatabase" as db
participant "students:List<Student>" as list
participant "sortedList:ArrayList" as sorted
participant "result:CommandResult" as res

Caller -> sort : execute(db, storage)
activate sort

sort -> sort : execute(db)
activate sort

sort -> db : getAllStudents()
activate db
db --> sort : students
deactivate db

sort -> sorted ** : new ArrayList<>(students)
activate sorted
sorted --> sort
deactivate sorted

sort -> sorted : sort(Comparator)
activate sorted
sorted --> sort
deactivate sorted

loop for each student in sortedList
    sort -> list : indexOf(student)
    activate list
    list --> sort : index
    deactivate list
    sort -> sort : format string with index + 1
end

sort -> res ** : new CommandResult(message, false)
activate res
res --> sort
deactivate res

sort --> sort : result
deactivate sort

sort --> Caller : result
deactivate sort
@enduml
